### PR TITLE
feat: Convert react-solid-state to typescript

### PR DESCRIPTION
**Pull request by alexmarucci**
Converting the react-solid-state to typescript.

### CODE REVIEW

**Comment by alexmarucci** [comment]
fixes #278

**Comment by ryansolid** [comment]
Awesome. I'm glad you took on this task as I probably wasn't going to get to it for a while.

It looks like the tests are failing. Just an issue with import (for some reason I was importing the .js extension specifically it looks like). If you don't get a chance to look at this I can do so tonight.

**Comment by alexmarucci** [comment]
Hey Ryan,

Happy New Year! I am excited by this project and I am happy to give my
contribution.

Sorry I am just catching up with emails. I think we just need to update
that import indeed.
I have a limited time I can spend on this today so feel free to update it
if it’s easier for you. I should be able to look at it this evening if not.


Have a great weekend,
Alessio

**Comment by alexmarucci** [comment]
Tests updated 👍

**Comment by alexmarucci** [comment]
Tests updated 👍

**Comment by alexmarucci** [comment]
Hmm, weird.. two of the solid-rx package tests are failing though it seems unrelated to my changes. Will investigate later today. Any idea? @ryansolid

**Comment by ryansolid** [comment]
Dont worry about those they occasionally fail. Some test runner timing issue.

**Comment by ryansolid** [comment]
Thanks so much

**Pull request merged**
