### PR TITLE
Improve `createMemo`'s signature

### LINKED ISSUE #216: Improve createMemo's signature
Currently `createMemo`'s signature looks like:

```typescript
export declare function createMemo<T>(fn: (v?: T) => T, value?: T, areEqual?: boolean | ((prev: T, next: T) => boolean)): () => T;
```

By adding two more signatures the relationship between `value` and `v` can be better shown:

```typescript
export declare function createMemo<T>(fn: (v: T) => T, value: T, areEqual?: boolean | ((prev: T, next: T) => boolean)): () => T;
export declare function createMemo<T>(fn: (v?: T) => T, value: undefined, areEqual?: boolean | ((prev: T, next: T) => boolean)): () => T;
```

### PR DESCRIPTION
**Pull request by Koxiaet**
Fixes #216. I probably should've done a PR in the first place.

### CODE REVIEW

**Comment by ryansolid** [comment]
This doesn't build. There are places where it complains about not passing arguments.

**Comment by Koxiaet** [comment]
Sorry about that, I've fixed it now.

**Comment by ryansolid** [comment]
I don't know, it's still broken. It really doesn't like this. The tests seem to fail in the same place. Do you see different locally?.. npm test from the root directory should run all the tests.

**Comment by Koxiaet** [comment]
I didn't run the tests earlier, my bad. The issue was with Typescript's inference inferring the incorrect form of `createMemo`, and was solved by reordering the overloads. It _should_ all work now hopefully.

**Comment by ryansolid** [comment]
Thank you for working through this with me.

**Pull request merged**
